@url = http://localhost:8080/api

POST {{url}}/vat-rate
Content-Type: application/json
Accept: application/json

{
    "rate": 11.10,
    "year": 2019,
    "month": 10,
    "is_active": true
}

####
DELETE {{url}}/vat-rate/cf17704e-3316-4d8a-abba-de3629857195
Content-Type: application/json
Accept: application/json
